environment: DEV
spring:
  profiles: DEV
  application:
    name: eureka-service-discovery
server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
---
environment: PROD
spring:
  profiles: PROD
  application:
    name: eureka-service-discovery
server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0